name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/DesktopWallpaperApp/DesktopWallpaperApp.csproj
      
    - name: Build
      run: dotnet build src/DesktopWallpaperApp/DesktopWallpaperApp.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test src/DesktopWallpaperApp/DesktopWallpaperApp.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
  release:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Publish Windows x64
      run: |
        dotnet publish src/DesktopWallpaperApp/DesktopWallpaperApp.csproj `
          --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output ./publish/win-x64 `
          --property:PublishSingleFile=true `
          --property:IncludeNativeLibrariesForSelfExtract=true
          
    - name: Create Release Archive
      run: |
        Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./DesktopWallpaperApp-win-x64.zip
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DesktopWallpaperApp-win-x64
        path: ./DesktopWallpaperApp-win-x64.zip